version: "3.3"
services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: bankDB
    environment:
      MYSQL_DATABASE: 'test_bank'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root123'
      MYSQL_ROOT_PASSWORD: 'root123'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image : app-bank:latest
    restart: always
    ports:
      - 80:8000